// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb3D8f5MzPigMO6MtXTuN_NWD50HTrkAI',
    appId: '1:609296028894:web:bf7dd7477e4dee7e9cde4f',
    messagingSenderId: '609296028894',
    projectId: 'taskly-9ef7d',
    authDomain: 'taskly-9ef7d.firebaseapp.com',
    storageBucket: 'taskly-9ef7d.firebasestorage.app',
    measurementId: 'G-EXK8CBJXVV',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf96YicUGpsVeERbkR0B95U6cyGA0rwwM',
    appId: '1:609296028894:ios:47dc690f5c9b51b29cde4f',
    messagingSenderId: '609296028894',
    projectId: 'taskly-9ef7d',
    storageBucket: 'taskly-9ef7d.firebasestorage.app',
    iosBundleId: 'com.jaival.taskly',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf96YicUGpsVeERbkR0B95U6cyGA0rwwM',
    appId: '1:609296028894:ios:47dc690f5c9b51b29cde4f',
    messagingSenderId: '609296028894',
    projectId: 'taskly-9ef7d',
    storageBucket: 'taskly-9ef7d.firebasestorage.app',
    iosBundleId: 'com.jaival.taskly',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCALRk8bMo6Uj16_RIXPn3RrOG5sxxAZV8',
    appId: '1:609296028894:android:aefe919f51ec15b79cde4f',
    messagingSenderId: '609296028894',
    projectId: 'taskly-9ef7d',
    storageBucket: 'taskly-9ef7d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb3D8f5MzPigMO6MtXTuN_NWD50HTrkAI',
    appId: '1:609296028894:web:1858f4bc6d4f29559cde4f',
    messagingSenderId: '609296028894',
    projectId: 'taskly-9ef7d',
    authDomain: 'taskly-9ef7d.firebaseapp.com',
    storageBucket: 'taskly-9ef7d.firebasestorage.app',
    measurementId: 'G-GEJQERGR2D',
  );
}
